name: Production Pipeline

on:
  push:
    branches: [ "master" ]
    paths:
      - 'apps/bot/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'ecosystem.config.js'
    tags:
      - "khaxyrewrite@*"
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


permissions:
  contents: read
  pull-requests: write

jobs:
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'
      - uses: pnpm/action-setup@v2
        with:
          version: '10.11.1'
      - run: pnpm install
      - run: pnpm db:generate
      - run: pnpm type-check
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'
      - uses: pnpm/action-setup@v2
        with:
          version: '10.11.1'
      - run: pnpm install
      - run: pnpm lint
  i18n-check:
    name: i18n Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'
      - uses: pnpm/action-setup@v2
        with:
          version: '10.11.1'
      - run: pnpm install
      - run: pnpm --filter khaxyrewrite run i18n:check